"""Add default_project_id to tenants

Revision ID: 8232161c931e
Revises: 1533dd8ff334
Create Date: 2025-09-01 14:07:22.303398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8232161c931e'
down_revision: Union[str, None] = '1533dd8ff334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('default_project_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'default_project_id')
    # ### end Alembic commands ###
