"""Add question answer audit table clean

Revision ID: bbc5f25d9ea8
Revises: 206c44af0dc8
Create Date: 2025-08-22 19:00:09.808882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc5f25d9ea8'
down_revision: Union[str, None] = '206c44af0dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_answer_audits',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('changed_by_user', sa.UUID(), nullable=True),
    sa.Column('change_source', sa.String(length=50), nullable=False),
    sa.Column('ai_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('chromadb_relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('previous_answer_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.CheckConstraint("change_source IN ('ai_initial', 'user_edit', 'user_create')", name='check_change_source'),
    sa.CheckConstraint("change_type IN ('create', 'edit', 'ai_generate')", name='check_change_type'),
    sa.ForeignKeyConstraint(['changed_by_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answer_audits')
    # ### end Alembic commands ###
